In [1]:
import numpy as np

In [7]:
array_1d = np.array([0,1,2,3,4,5,6,7,8,9])
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
array_2d = np.random.randint(1, 21, size=(3, 3)) # between 1 and 20.
print(array_2d)

[[14 16  8]
 [ 6 10 12]
 [ 6 18  8]]


In [8]:
array_3d = np.full((2, 3, 4), 1)
print(array_3d)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [11]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
sumis = np.add(array1, array2)
print(sumis)

[5 7 9]


In [13]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
product = np.multiply(array1, array2)
print(product)

[ 4 10 18]


In [15]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix1, matrix2)
print(dot_product)

[[19 22]
 [43 50]]


In [21]:
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_dev}")

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [20]:
array_2d = np.array([[1,3,5,7],[2,4,6,8]])
max_value = np.max(array_2d)
min_value = np.min(array_2d)
print(f"Maximum Value: {max_value}")
print(f"Maximum Value: {min_value}")d

Maximum Value: 8
Maximum Value: 1


In [22]:
# normal distribution array
arr = np.random.normal(0, 1, 1000)
print(arr)

[ 3.77066684e-01 -5.93072810e-01 -8.46328986e-01  5.28870994e-01
 -5.13376156e-01 -1.23373548e+00 -7.48278696e-01  1.44153953e+00
  1.71130937e+00 -8.78866909e-01 -2.10146596e+00 -3.28641166e-01
 -2.71600412e-01 -1.66958228e-01 -2.12411331e+00 -1.66844628e+00
 -1.24484245e+00 -4.29464350e-01 -3.47124536e-01  1.03070806e+00
 -9.94006945e-01  1.37221253e+00  7.73121087e-01  7.59930308e-02
 -3.29905457e+00  1.09448904e+00 -4.29870621e-01  1.42627010e+00
 -2.04506905e+00 -1.34477477e+00  2.66664434e-01 -1.40305381e-01
  9.39867812e-01 -1.19901070e+00 -8.94175205e-02 -1.58813913e+00
 -2.95753156e-01 -2.84245445e-01 -4.51282353e-01  6.47211729e-01
 -1.39482561e+00  2.39157121e-01  5.07975195e-01  8.97702410e-01
  6.88970580e-01  1.68589155e+00 -1.53377350e-01  9.92699508e-01
  1.09715133e+00  1.23617180e+00 -3.66026860e-01  6.92724708e-01
  2.37003589e-01 -2.42966156e+00 -1.27538374e-01  1.13599115e-01
 -3.99204214e-01 -1.78019969e-01  1.68782042e-01  8.07939679e-01
 -7.71929368e-01  5.52661

In [24]:
# Uniform distribution array
arr = np.random.randint(10, 51, size=(5, 5))
print(arr)

[[44 34 10 48 46]
 [39 39 48 38 45]
 [25 33 24 16 20]
 [22 41 23 39 30]
 [12 36 28 32 17]]


In [26]:
# cumulative sum
arr = np.array([1, 2, 3, 4, 5])
sumis = np.cumsum(arr)
print(sumis)

[ 1  3  6 10 15]


In [27]:
arr= np.random.randint(1, 100, size=(5, 5))
correlation_matrix = np.corrcoef(arr, rowvar=False)
print(correlation_matrix)


[[ 1.         -0.81444407  0.89605449  0.23494998  0.18496109]
 [-0.81444407  1.         -0.83180224 -0.24225236 -0.47229557]
 [ 0.89605449 -0.83180224  1.          0.13151747 -0.02838876]
 [ 0.23494998 -0.24225236  0.13151747  1.         -0.10238963]
 [ 0.18496109 -0.47229557 -0.02838876 -0.10238963  1.        ]]


In [28]:
# Simulate rolling the die 1000 times
rolls = np.random.randint(1, 7, size=1000)
counts = np.bincount(rolls) # count frequency

for outcome, frequency in enumerate(counts[1:], start=1):
    print(f"Outcome {outcome}: {frequency} times")

Outcome 1: 186 times
Outcome 2: 166 times
Outcome 3: 141 times
Outcome 4: 177 times
Outcome 5: 152 times
Outcome 6: 178 times
