### Linear Algebra

In [1]:
import numpy as np

zero_matrix = np.zeros((3, 3))
print("Zero Matrix:\n", zero_matrix)

identity_matrix = np.eye(3)
print("\nIdentity Matrix:\n", identity_matrix)

random_matrix = np.random.rand(3, 3)
print("\nRandom Matrix:\n", random_matrix)


Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Matrix:
 [[0.89066611 0.19038602 0.81390163]
 [0.91533165 0.77836764 0.22467622]
 [0.76895899 0.35243025 0.27702523]]


#### Matrices operations

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

addition = A + B
print("\nAddition:\n", addition)

subtraction = A - B
print("\nSubtraction:\n", subtraction)

# element-wise multiplication
multiplication = A * B
print("\nElement-wise Multiplication:\n", multiplication)

matrix_multiplication = np.dot(A, B)
print("\nMatrix Multiplication:\n", matrix_multiplication)



Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


#### Transpose, Determinant, Inverse

In [9]:
transpose_A = A.T
print("\nTranspose of A:\n", transpose_A)

det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

C = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
inverse_C = np.linalg.inv(C)
print("\nInverse of C:\n", inverse_C)


Transpose of A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant of A: -9.51619735392994e-16

Inverse of C:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


#### Implement matrix factorization methods

In [10]:
# LU Decomposition
import scipy.linalg

P, L, U = scipy.linalg.lu(A)
print("LU Decomposition:\nP:\n", P, "\nL:\n", L, "\nU:\n", U)

# QR Decomposition
Q, R = np.linalg.qr(A)
print("QR Decomposition:\nQ:\n", Q, "\nR:\n", R)


LU Decomposition:
P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 
L:
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]] 
U:
 [[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
QR Decomposition:
Q:
 [[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]] 
R:
 [[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]


#### Eigenvalues and eigenvectors

In [15]:
eigenvalues, eigenvectors = np.linalg.eig(random_matrix)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [ 1.74940261 -0.1798363   0.37649267]
Eigenvectors:
 [[-0.58779527 -0.59731165  0.41117866]
 [-0.66175486  0.40879718 -0.91035208]
 [-0.46537858  0.69000266 -0.04681013]]


#### Matrix Decomposition

In [16]:
# Data matrix
data_matrix = np.random.rand(10, 5)

# Mean centering
data_matrix_centered = data_matrix - np.mean(data_matrix, axis=0)

# SVD
U, S, Vt = np.linalg.svd(data_matrix_centered, full_matrices=False)

# PCA
principal_components = Vt.T

print("Principal Components:\n", principal_components)


Principal Components:
 [[-0.50985226  0.35741887 -0.18084235  0.20479103 -0.73325241]
 [-0.51852609  0.1445345  -0.53646063  0.19877161  0.61882171]
 [-0.48132727  0.32722052  0.72862941 -0.27072355  0.23886969]
 [ 0.46491472  0.7542749   0.08156733  0.43267739  0.14512313]
 [-0.15283887 -0.41875725  0.37676516  0.81120251  0.03579313]]


### Calculus

#### Numerical Differentiation

In [17]:
def f(x):
    return x**2


x = np.linspace(0, 10, 100)
dx = x[1] - x[0]
numerical_derivative = np.gradient(f(x), dx)

print("Numerical Derivative:\n", numerical_derivative)


Numerical Derivative:
 [ 0.1010101   0.2020202   0.4040404   0.60606061  0.80808081  1.01010101
  1.21212121  1.41414141  1.61616162  1.81818182  2.02020202  2.22222222
  2.42424242  2.62626263  2.82828283  3.03030303  3.23232323  3.43434343
  3.63636364  3.83838384  4.04040404  4.24242424  4.44444444  4.64646465
  4.84848485  5.05050505  5.25252525  5.45454545  5.65656566  5.85858586
  6.06060606  6.26262626  6.46464646  6.66666667  6.86868687  7.07070707
  7.27272727  7.47474747  7.67676768  7.87878788  8.08080808  8.28282828
  8.48484848  8.68686869  8.88888889  9.09090909  9.29292929  9.49494949
  9.6969697   9.8989899  10.1010101  10.3030303  10.50505051 10.70707071
 10.90909091 11.11111111 11.31313131 11.51515152 11.71717172 11.91919192
 12.12121212 12.32323232 12.52525253 12.72727273 12.92929293 13.13131313
 13.33333333 13.53535354 13.73737374 13.93939394 14.14141414 14.34343434
 14.54545455 14.74747475 14.94949495 15.15151515 15.35353535 15.55555556
 15.75757576 15.95959596 16.

#### Implement forward, backward, and central difference methods

In [19]:
forward_difference = (f(x + dx) - f(x)) / dx

backward_difference = (f(x) - f(x - dx)) / dx

central_difference = (f(x + dx) - f(x - dx)) / (2 * dx)

print("Forward Difference:\n", forward_difference)
print("Backward Difference:\n", backward_difference)
print("Central Difference:\n", central_difference)


Forward Difference:
 [ 0.1010101   0.3030303   0.50505051  0.70707071  0.90909091  1.11111111
  1.31313131  1.51515152  1.71717172  1.91919192  2.12121212  2.32323232
  2.52525253  2.72727273  2.92929293  3.13131313  3.33333333  3.53535354
  3.73737374  3.93939394  4.14141414  4.34343434  4.54545455  4.74747475
  4.94949495  5.15151515  5.35353535  5.55555556  5.75757576  5.95959596
  6.16161616  6.36363636  6.56565657  6.76767677  6.96969697  7.17171717
  7.37373737  7.57575758  7.77777778  7.97979798  8.18181818  8.38383838
  8.58585859  8.78787879  8.98989899  9.19191919  9.39393939  9.5959596
  9.7979798  10.         10.2020202  10.4040404  10.60606061 10.80808081
 11.01010101 11.21212121 11.41414141 11.61616162 11.81818182 12.02020202
 12.22222222 12.42424242 12.62626263 12.82828283 13.03030303 13.23232323
 13.43434343 13.63636364 13.83838384 14.04040404 14.24242424 14.44444444
 14.64646465 14.84848485 15.05050505 15.25252525 15.45454545 15.65656566
 15.85858586 16.06060606 16.262

#### Numerical Integration

#### Trapezoidal rule for integration

In [23]:
def g(x):
    return np.sin(x)

integral_trapezoidal = np.trapz(g(x), x)

print("Integral (Trapezoidal Rule): ", integral_trapezoidal)


Integral (Trapezoidal Rule):  1.8375075863321546


#### Simpson's rule for integration

In [24]:
integral_simpsons = scipy.integrate.simps(g(x), x)
print("Integral (Simpson's Rule): ", integral_simpsons)

Integral (Simpson's Rule):  1.8390764529333192


### Partial derivative

In [25]:
def h(x, y): # Multivariable function
    return x**2 + y**2

# with respect to x
def partial_x(x, y, dx=1e-5):
    return (h(x + dx, y) - h(x, y)) / dx

# with respect to y
def partial_y(x, y, dy=1e-5):
    return (h(x, y + dy) - h(x, y)) / dy


x, y = np.meshgrid(np.linspace(-10, 10, 100), np.linspace(-10, 10, 100))
partial_x_result = partial_x(x, y)
partial_y_result = partial_y(x, y)

print("Partial Derivative w.r.t. x:\n", partial_x_result)
print("Partial Derivative w.r.t. y:\n", partial_y_result)


Partial Derivative w.r.t. x:
 [[-19.99999    -19.5959496  -19.19190919 ...  19.19192919  19.5959696
   20.00001   ]
 [-19.99999    -19.5959496  -19.19190919 ...  19.19192919  19.5959696
   20.00001   ]
 [-19.99999    -19.5959496  -19.19190919 ...  19.19192919  19.5959696
   20.00001   ]
 ...
 [-19.99999    -19.5959496  -19.19190919 ...  19.19192919  19.5959696
   20.00001   ]
 [-19.99999    -19.5959496  -19.19190919 ...  19.19192919  19.5959696
   20.00001   ]
 [-19.99999    -19.5959496  -19.19190919 ...  19.19192919  19.5959696
   20.00001   ]]
Partial Derivative w.r.t. y:
 [[-19.99999    -19.99999    -19.99999    ... -19.99999    -19.99999
  -19.99999   ]
 [-19.5959496  -19.5959496  -19.5959496  ... -19.5959496  -19.5959496
  -19.5959496 ]
 [-19.19190919 -19.19190919 -19.19190919 ... -19.19190919 -19.19190919
  -19.19190919]
 ...
 [ 19.19192919  19.19192919  19.19192919 ...  19.19192919  19.19192919
   19.19192919]
 [ 19.5959696   19.5959696   19.5959696  ...  19.5959696   19.5959696