In [ ]:
import numpy as np

In [3]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
sub_arr = arr[1:4, 1:4]
print(sub_arr)


[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [4]:
arr = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
    [[13, 14], [15, 16], [17, 18]],
    [[19, 20], [21, 22], [23, 24]]
])
sub_array = arr[:2, :, 1]
print(sub_array)

[[ 2  4  6]
 [ 8 10 12]]


In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
fancy_indexed_elements = arr[[1, 3, 4, 7]]
print(fancy_indexed_elements)

[1 3 4 7]


In [8]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
fancy_indexed = arr[[0, 2, 3], :][:, [1, 3]]
print(fancy_indexed)

[[ 2  4]
 [12 14]
 [17 19]]


In [9]:
array = np.array([5, 10, 15, 20, 25, 30])
elements = array_1d[array_1d > 10]
print(elements)

[15 20 25 30]


In [11]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
arr[array_2d > 15] = 0
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


##### Broadcasting

In [12]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
array_1d = np.array([1, 2, 3])
broadcast_sum = array_2d + array_1d
print(broadcast_sum)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [13]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
array_1d = np.array([1, 2, 3])
broadcast_product = array_2d * array_1d
print(broadcast_product)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [16]:
arraya = np.array([
    [1],
    [2],
    [3]
])
arrayb = np.array([[4, 5, 6, 7]])
broadcast_addition = arraya + arrayb
print(broadcast_addition)

[[ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


In [17]:
array_3d = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])
array_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
broadcast_add_3d = array_3d + array_2d
print(broadcast_add_3d)

[[[ 2  4  6  8]
  [10 12 14 16]
  [18 20 22 24]]

 [[14 16 18 20]
  [22 24 26 28]
  [30 32 34 36]]]


#### some more

In [18]:
import numpy as np

array_2d_task1 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
sliced_array_task1 = array_2d_task1[::2, ::2]
array_1d_task1 = np.array([1, 2, 3])
broadcast_sum_sliced_task1 = sliced_array_task1 + array_1d_task1[:sliced_array_task1.shape[1]]

array_3d_task2 = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
    [[13, 14], [15, 16], [17, 18]],
    [[19, 20], [21, 22], [23, 24]]
])
sub_array_3d_task2 = array_3d_task2[:2, :, :]
array_2d_task2 = np.array([
    [1, 1],
    [1, 1],
    [1, 1]
])
broadcast_subtract_3d_task2 = sub_array_3d_task2 - array_2d_task2

array_2d_task3 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
diagonal_elements_task3 = np.diag(array_2d_task3)

array_2d_task4 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
reversed_rows_task4 = array_2d_task4[:, ::-1]

array_3d_task5 = np.array([
    [[1, 2, 3, 4, 5, 6],
     [7, 8, 9, 10, 11, 12],
     [13, 14, 15, 16, 17, 18],
     [19, 20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29, 30]],
    [[31, 32, 33, 34, 35, 36],
     [37, 38, 39, 40, 41, 42],
     [43, 44, 45, 46, 47, 48],
     [49, 50, 51, 52, 53, 54],
     [55, 56, 57, 58, 59, 60]],
    [[61, 62, 63, 64, 65, 66],
     [67, 68, 69, 70, 71, 72],
     [73, 74, 75, 76, 77, 78],
     [79, 80, 81, 82, 83, 84],
     [85, 86, 87, 88, 89, 90]],
    [[91, 92, 93, 94, 95, 96],
     [97, 98, 99, 100, 101, 102],
     [103, 104, 105, 106, 107, 108],
     [109, 110, 111, 112, 113, 114],
     [115, 116, 117, 118, 119, 120]]
])
sub_array_3d_task5 = array_3d_task5[:2, :3, :4]
array_1d_task5 = np.array([1, 2, 3, 4])
broadcast_add_1d_task5 = sub_array_3d_task5 + array_1d_task5

array_2d_task6 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
array_2d_task6[:, -1] = array_2d_task6[:, 0] + array_2d_task6[:, 1]

print("Task 1: Extract every second row and every second column, then add a 1D array to each row of the sliced array")
print(sliced_array_task1)
print(broadcast_sum_sliced_task1)

print("\nTask 2: Extract a sub-array from a 3D array of shape (4, 3, 2) and use broadcasting to subtract a 2D array from each slice along the third axis")
print(sub_array_3d_task2)
print(broadcast_subtract_3d_task2)

print("\nTask 3: Extract the diagonal elements and create a 1D array")
print(diagonal_elements_task3)

print("\nTask 4: Use slicing to reverse the order of elements in each row of a 2D array")
print(reversed_rows_task4)

print("\nTask 5: Extract a sub-array of shape (2, 3, 4) and use broadcasting to add a 1D array of shape (4,) to each row along the third axis")
print(sub_array_3d_task5)
print(broadcast_add_1d_task5)

print("\nTask 6: Set the last column to the sum of the first two columns for each row in a 2D array")
print(array_2d_task6)


Task 1: Extract every second row and every second column, then add a 1D array to each row of the sliced array
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
[[ 2  5  8]
 [12 15 18]
 [22 25 28]]

Task 2: Extract a sub-array from a 3D array of shape (4, 3, 2) and use broadcasting to subtract a 2D array from each slice along the third axis
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

Task 3: Extract the diagonal elements and create a 1D array
[ 1  7 13 19 25]

Task 4: Use slicing to reverse the order of elements in each row of a 2D array
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]

Task 5: Extract a sub-array of shape (2, 3, 4) and use broadcasting to add a 1D array of shape (4,) to each row along the third axis
[[[ 1  2  3  4]
  [ 7  8  9 10]
  [13 14 15 16]]

 [[31 32 33 34]
  [37 38 39 40]
  [43 44 45 46]]]
[[[ 2  4  6  8]
  [ 8 10 12 14]
  [14 16 18 20]]

 [[32 34 3